# Задача потребителя

## Получение данных

Параметры модулирования:


>  Станция
    Novosibirsk(MRK)
    
    X
    452.28865
    Y
    3635.913158
    Z
    5203.397861

>  Спутники

*   1. 1/2
*   2. 2/1
*   3. 3/12
*   4. 4/6


Выполним импорты нужных модулей

In [0]:
import numpy as np
import pandas as pd
from scipy.optimize import fsolve

Запомним координаты станции как вектор для проверки в конце

In [0]:
 required_coordinates = np.array([
        452.28865,
        3635.913158,
        5203.397861,
 ])

Загрузим excel-файл с данными модуляции

In [4]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('Загруженный "{name}" размером {length} байт'.format(
      name=fn, length=len(uploaded[fn])))

Saving reports.xls to reports (1).xls
Загруженный "reports.xls" размером 306688 байт


Откроем файл в виде таблицы, чекнем превью

In [6]:
mod_data = pd.read_excel("reports.xls")
mod_data.head()

Time_mom  N_Sat            P1        Sat_X         Sat_Y        Sat_Z
0  01:47:00      1  23640.463423 -1403.143993  25077.821790 -4577.880104
1  01:47:30      1  23614.250832 -1400.494773  25096.862175 -4472.742878
2  01:48:00      1  23588.052424 -1397.739724  25115.469797 -4367.509327
3  01:48:30      1  23561.868740 -1394.880788  25133.643881 -4262.181717
4  01:49:00      1  23535.700307 -1391.919910  25151.383669 -4156.762322

найдем моменты, когда одновременно в зоне видимости хотя бы три спутника

In [7]:
by_time = mod_data.groupby(by='Time_mom')['N_Sat'].count() 
observed_more_than_two = by_time[by_time>2]
len(observed_more_than_two)

405

таких моментов около 400, а вот сразу четыре спутника никогда не видны

In [8]:
len(observed_more_than_two[observed_more_than_two>3])   # одновременно 4 никогда не наблюдаются

0

возьмем какой-нибудь рандомный момент

In [9]:
sample_time = observed_more_than_two.index[78]
sample = mod_data[mod_data['Time_mom'] == sample_time]
sample

Time_mom  N_Sat            P1         Sat_X         Sat_Y         Sat_Z
785  05:25:00      2  19052.577323   2184.905275  15349.310978  20129.689073
786  05:25:00      1  21106.787484 -11915.881636   3162.669722  22300.104699
787  05:25:00      3  21880.141257  16211.479975  18786.485990   6124.669437

## Предустановки

Выделение из записи таблицы вектора координат спутника и расстояния

In [0]:
def get_Us_and_P(row):
    return np.array([row['Sat_X'],
                     row['Sat_Y'],
                     row['Sat_Z'],]), row['P1']

Евклидово расстояние между двумя векторами

In [0]:
def distance(v1,v2):
    return np.sqrt(np.sum((v1-v2)**2))

Так будем рассчитывать направляющие косинусы по три за раз (все парамеры - векторы)

In [0]:
def dir_cos(Us,Ur,Ro0):
    return (Us-Ur)/Ro0

## I способ расчета

Выделим нужные данные по спутникам из образца

In [13]:
sat_data = [get_Us_and_P(sample.iloc[i]) for i in range(3)]
sat_data

[(array([ 2184.90527483, 15349.3109776 , 20129.68907288]), 19052.5773226953),
 (array([-11915.8816357 ,   3162.66972196,  22300.10469944]), 21106.787484125),
 (array([16211.47997461, 18786.48599038,  6124.66943681]), 21880.1412569171)]

Так выглядит система уравнений, где неизвестные - координаты потребителя. Уравнения должны быть приведены к нулю.

In [0]:
def to_solve_Ur_0(v,Sat_data):
    return [distance(v,u) - p for u,p in Sat_data]

При подстановке в систему искомых координат результат должен быть нулевым для каждого уравнения.

In [15]:
to_solve_Ur_0(required_coordinates,sat_data)

[-0.02321069562822231, -0.0828553766150435, 0.002930710372311296]

Посмотрим сколько времени займет решение системы

In [16]:
%time Ur_0 = fsolve(to_solve_Ur_0, np.array([1.,1.,1.]), args=(sat_data))

Ur_0              

CPU times: user 1.37 ms, sys: 0 ns, total: 1.37 ms
Wall time: 3.64 ms


array([ 450.6806568 , 3637.66420946, 5202.18098915])

Разделим координаты и расстояния в  данных спутников. Введем опорные расстояния - с обрезанной дробной частью

In [17]:
Ro = np.array([P_i for Us_i,P_i in sat_data])
Ro_0 = Ro.astype(int).astype(np.float64)
Us = [Us_i for Us_i,P in sat_data]
Us

[array([ 2184.90527483, 15349.3109776 , 20129.68907288]),
 array([-11915.8816357 ,   3162.66972196,  22300.10469944]),
 array([16211.47997461, 18786.48599038,  6124.66943681])]

Ищем направляющие косинусы

In [18]:
dir_cosines = [dir_cos(*vals) for vals in zip(Us,[Ur_0]*3,Ro_0)]
dir_cosines

[array([0.09102586, 0.61472007, 0.78351397]),
 array([-0.58592639, -0.02250519,  0.81009778]),
 array([0.72032904, 0.69235931, 0.04216126])]

Так выглядит система уравнений для нахождения дельт.

In [0]:
def to_solve_deltas(deltas,cosines,ro_0,ro):
    return [(-p+p0+np.sum(np.array(deltas)*cos)) for cos,p0,p in zip(cosines,ro_0,ro)]

In [20]:
to_solve_deltas([.0,.0,.0,],dir_cosines,Ro_0,Ro)

[-0.5773226952987898, -0.787484125001356, -0.14125691710069077]

Ищем дельты

In [21]:
%time deltas = fsolve(to_solve_deltas,[.0,.0,.0],args=(dir_cosines,Ro_0,Ro))
deltas

CPU times: user 980 µs, sys: 0 ns, total: 980 µs
Wall time: 1.12 ms


array([ 8.81696817, -9.40075801,  7.08804881])

Смотрим результаты

In [22]:
print('Без смещений')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0)
print('разности в координатах\n', abs(required_coordinates - Ur_0))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0))

Без смещений
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 450.6806568  3637.66420946 5202.18098915]
разности в координатах
 [1.6079932  1.75105146 1.21687185]
расстояние между реальной и предполагаемой точками
 2.6706928744430445


In [23]:
print('Со смещениями + delta')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0+deltas)
print('разности в координатах\n', abs(required_coordinates - Ur_0-deltas))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0+deltas))

Со смещениями + delta
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 459.49762497 3628.26345144 5209.26903796]
разности в координатах
 [7.20897497 7.64970656 5.87117696]
расстояние между реальной и предполагаемой точками
 12.039852551265334


In [24]:
print('Со смещениями - delta')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0-deltas)
print('разности в координатах\n', abs(required_coordinates - Ur_0+deltas))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0-deltas))

Со смещениями - delta
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 441.86368863 3647.06496747 5195.09294034]
разности в координатах
 [10.42496137 11.15180947  8.30492066]
расстояние между реальной и предполагаемой точками
 17.37856096396465


## II способ расчета

Воспользуемся некоторыми переменными, полученными ранее

In [25]:
print(sat_data)
print(Us)
print(Ro)

[(array([ 2184.90527483, 15349.3109776 , 20129.68907288]), 19052.5773226953), (array([-11915.8816357 ,   3162.66972196,  22300.10469944]), 21106.787484125), (array([16211.47997461, 18786.48599038,  6124.66943681]), 21880.1412569171)]
[array([ 2184.90527483, 15349.3109776 , 20129.68907288]), array([-11915.8816357 ,   3162.66972196,  22300.10469944]), array([16211.47997461, 18786.48599038,  6124.66943681])]
[19052.5773227  21106.78748413 21880.14125692]


Решая систему уравнений, ищем координаты потребителя. Берем только целочисленную часть и называем их опорными координатами.

In [26]:
%time Ur_0 = fsolve(to_solve_Ur_0, np.array([1.,1.,1.]), args=(sat_data)).astype(int).astype(np.float64)
Ur_0              

CPU times: user 814 µs, sys: 984 µs, total: 1.8 ms
Wall time: 2 ms


array([ 450., 3637., 5202.])

Вводим опорные расстояния как евклидовы расстояния между неточными координатами потребителя и координатами каждого спутника

In [27]:
Ro_0 = np.array([distance(Ur_0,Us_i) for Us_i in Us])
Ro_0

array([19053.18938669, 21106.52037058, 21881.09905038])

Ищем направляющие косинусы

In [28]:
dir_cosines = [dir_cos(*vals) for vals in zip(Us,[Ur_0]*3,Ro_0)]
dir_cosines

[array([0.0910559 , 0.61471656, 0.78347455]),
 array([-0.58587969, -0.02247316,  0.81008638]),
 array([0.72032396, 0.69235489, 0.04216742])]

Посмотрим, сколько времени займет решение системы уравнений для поиска дельт

In [29]:
%time deltas = fsolve(to_solve_deltas,[.0,.0,.0],args=(dir_cosines,Ro_0,Ro))
deltas

CPU times: user 1.1 ms, sys: 0 ns, total: 1.1 ms
Wall time: 1.54 ms


array([-0.6805129 , -0.66436613, -0.1808641 ])

Смотрим результаты для того самого образца

In [30]:
print('Без смещений')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0)
print('разности в координатах\n', abs(required_coordinates - Ur_0))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0))

Без смещений
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 450. 3637. 5202.]
разности в координатах
 [2.28865  1.086842 1.397861]
расстояние между реальной и предполагаемой точками
 2.8936412581359288


In [31]:
print('Со смещениями - delta')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0-deltas)
print('разности в координатах\n', abs(required_coordinates - Ur_0+deltas))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0-deltas))

Со смещениями - delta
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 450.6805129  3637.66436613 5202.1808641 ]
разности в координатах
 [1.6081371  1.75120813 1.2169969 ]
расстояние между реальной и предполагаемой точками
 2.6709392194085


In [32]:
print('Со смещениями + delta')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0+deltas)
print('разности в координатах\n', abs(required_coordinates - Ur_0-deltas))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0+deltas))

Со смещениями + delta
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 449.3194871  3636.33563387 5201.8191359 ]
разности в координатах
 [2.9691629  0.42247587 1.5787251 ]
расстояние между реальной и предполагаемой точками
 3.3892162980614353


## III способ расчета

Введем опорные расстояния - целочисленные части расстояний от каждого спутника до потребителя (станции)

In [0]:
Ro_0 = Ro.astype(int).astype(np.float64)

Ищем опорные координаты потребителя

In [34]:
%time Ur_0 = fsolve(to_solve_Ur_0, np.array([1.,1.,1.]), args=(list(zip(Us,Ro_0))))
Ur_0              

CPU times: user 1.81 ms, sys: 0 ns, total: 1.81 ms
Wall time: 1.93 ms


array([ 459.61470208, 3628.14362089, 5209.3568971 ])

Ищем направлющие косинусы

In [35]:
dir_cosines = [dir_cos(*vals) for vals in zip(Us,[Ur_0]*3,Ro_0)]
dir_cosines

[array([0.09055693, 0.61521979, 0.78313732]),
 array([-0.58634968, -0.0220541 ,  0.80975778]),
 array([0.71992072, 0.69279444, 0.0418333 ])]

Ищем дельты

In [36]:
%time deltas = fsolve(to_solve_deltas,[.0,.0,.0],args=(dir_cosines,Ro_0,Ro))
deltas

CPU times: user 1.2 ms, sys: 214 µs, total: 1.41 ms
Wall time: 3.04 ms


array([ 9.05382819, -9.64316787,  7.26578006])

смотрим результаты

In [37]:
print('Без смещений')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0)
print('разности в координатах\n', abs(required_coordinates - Ur_0))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0))

Без смещений
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 459.61470208 3628.14362089 5209.3568971 ]
разности в координатах
 [7.32605208 7.76953711 5.9590361 ]
расстояние между реальной и предполагаемой точками
 12.228935242532412


In [38]:
print('Со смещениями - delta')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0-deltas)
print('разности в координатах\n', abs(required_coordinates - Ur_0+deltas))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0-deltas))

Со смещениями - delta
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 450.56087389 3637.78678876 5202.09111704]
разности в координатах
 [1.72777611 1.87363076 1.30674396]
расстояние между реальной и предполагаемой точками
 2.8641372644435443


In [39]:
print('Со смещениями + delta')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0+deltas)
print('разности в координатах\n', abs(required_coordinates - Ur_0-deltas))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0+deltas))

Со смещениями + delta
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 468.66853027 3618.50045303 5216.62267716]
разности в координатах
 [16.37988027 17.41270497 13.22481616]
расстояние между реальной и предполагаемой точками
 27.320295284129973


In [40]:
np.array([ 452.28865,  -3635.913158, 5203.397861]).astype(int).astype(np.float64)

array([  452., -3635.,  5203.])

## Результаты

Дельта отображается без косяков

In [41]:
print('Δ','δ')

Δ δ


Напишем функции, соответствующие 1,2,3-му методам.

На входе у них список выборок из таблиц (данных о спутниках в опр момент времени)

На выходе - найденные координаты потребителя и дельты

In [0]:
def ingot():
    return    {'Xr без коррекции':[],
               'Yr без коррекции':[],
               'Zr без коррекции':[],
               'ΔX':[],
               'ΔY':[],
               'ΔZ':[],}

In [0]:
def method_1(samples: list):
    res = ingot()
    for sample in samples:
        sat_data = [get_Us_and_P(sample.iloc[i]) for i in range(3)]
        Ur_0 = fsolve(to_solve_Ur_0, np.array([1.,1.,1.]), args=(sat_data))
        Ro = np.array([P_i for Us_i,P_i in sat_data])
        Ro_0 = np.floor(Ro)
        Us = [Us_i for Us_i,P in sat_data]
        dir_cosines = [dir_cos(*vals) for vals in zip(Us,[Ur_0]*3,Ro_0)]
        deltas = fsolve(to_solve_deltas,[.0,.0,.0],args=(dir_cosines,Ro_0,Ro))
        for i,ax in enumerate(('X','Y','Z')):
           res[ax+'r без коррекции'].append(Ur_0[i])
           res['Δ'+ax].append(deltas[i])
    return res

In [0]:
def method_2(samples: list):
    res = ingot()
    for sample in samples:
        sat_data = [get_Us_and_P(sample.iloc[i]) for i in range(3)]
        Ro = np.array([P_i for Us_i,P_i in sat_data])
        Us = [Us_i for Us_i,P in sat_data]
        Ur_0 = np.floor(fsolve(to_solve_Ur_0, np.array([1.,1.,1.]), args=(sat_data)))
        Ro_0 = np.array([distance(Ur_0,Us_i) for Us_i in Us])
        dir_cosines = [dir_cos(*vals) for vals in zip(Us,[Ur_0]*3,Ro_0)]
        deltas = fsolve(to_solve_deltas,[.0,.0,.0],args=(dir_cosines,Ro_0,Ro))
        for i,ax in enumerate(('X','Y','Z')):
           res[ax+'r без коррекции'].append(Ur_0[i])
           res['Δ'+ax].append(deltas[i])
    return res

In [0]:
def method_3(samples: list):
    res = ingot()
    for sample in samples:
        sat_data = [get_Us_and_P(sample.iloc[i]) for i in range(3)]
        Ro = np.array([P_i for Us_i,P_i in sat_data])
        Us = [Us_i for Us_i,P in sat_data]
        Ro_0 = np.floor(Ro)
        Ur_0 = fsolve(to_solve_Ur_0, np.array([1.,1.,1.]), args=(list(zip(Us,Ro_0))))
        dir_cosines = [dir_cos(*vals) for vals in zip(Us,[Ur_0]*3,Ro_0)]
        deltas = fsolve(to_solve_deltas,[.0,.0,.0],args=(dir_cosines,Ro_0,Ro))
        for i,ax in enumerate(('X','Y','Z')):
           res[ax+'r без коррекции'].append(Ur_0[i])
           res['Δ'+ax].append(deltas[i])
    return res

In [0]:
from random import sample as some_samples

Выберем список из 12 моментов времени, глянем превью

In [47]:
n_sample_time = some_samples(observed_more_than_two.index.to_list(), 12)
samples = [mod_data[mod_data['Time_mom'] == sample_time] for sample_time in n_sample_time]
samples[4:8]

[     Time_mom  N_Sat            P1         Sat_X         Sat_Y         Sat_Z
 989  05:59:00      2  19229.039986  -2387.906537  11335.717867  22593.069238
 990  05:59:00      1  22502.501863 -16551.387248   -453.214231  19363.615199
 991  05:59:00      3  20625.332488  14322.636232  16923.566654  12717.123746,
      Time_mom  N_Sat            P1         Sat_X         Sat_Y         Sat_Z
 854  05:36:30      2  19047.152234    775.188087  13961.171437  21205.824546
 855  05:36:30      1  21555.207230 -13483.185776   1797.208424  21544.902119
 856  05:36:30      3  21419.485318  15767.870829  18252.538300   8456.348608,
       Time_mom  N_Sat            P1         Sat_X         Sat_Y         Sat_Z
 1380  07:04:30      2  20922.612073 -13202.848088   5713.618322  20918.765632
 1381  07:04:30      3  19322.975899   5987.220552  12559.046839  21424.336160
 1382  07:04:30      4  21869.145032  19894.414228  12608.552221   9648.054238,
       Time_mom  N_Sat            P1         Sat_X       

составим удобоваримые таблички для результатов расчета тремя методами по 12 образцов каждый

In [0]:
results = [pd.DataFrame(eval('method_'+str(i+1)+'(samples)')) for i in range(3)]

for df in results:
    to_pop = list()
    for sign in ('+','-'):
        for i,ax in enumerate(('X','Y','Z')):
            tmp = eval("df[ax+'r без коррекции']"+sign+
                       "df['Δ'+ax] - required_coordinates[i]" )
            df['{a}r {s} Δ{a} - {a} реал.'.format(a=ax,s=sign)] = tmp
            hs = str(i)+sign
            to_pop.append(hs)
            df[hs] = tmp**2
        df['Расстояние от реал до (Ur{s}Δ)'.format(s=sign)] = np.sqrt(
            df['0'+sign]+df['1'+sign]+df['2'+sign]
        )
    for hs in to_pop:
        df.pop(hs)
    to_pop.clear()

In [49]:
results[0]

Xr без коррекции  ...  Расстояние от реал до (Ur-Δ)
0         187.033453  ...                    926.093923
1         452.217320  ...                     23.163897
2         452.884814  ...                     16.249046
3         453.103848  ...                      8.449292
4         450.889587  ...                     36.630254
5         450.819970  ...                     25.762828
6         210.281750  ...                    767.977302
7         163.284556  ...                    942.116033
8         450.621827  ...                     61.282655
9         450.892094  ...                      2.385199
10        452.061263  ...                     12.316908
11        450.603553  ...                     27.761083

[12 rows x 14 columns]

In [50]:
results[1]

Xr без коррекции  ...  Расстояние от реал до (Ur-Δ)
0              187.0  ...                    855.810697
1              452.0  ...                      2.156297
2              452.0  ...                      1.326645
3              453.0  ...                      2.213453
4              450.0  ...                      2.849075
5              450.0  ...                      2.603228
6              210.0  ...                    792.402620
7              163.0  ...                    919.125266
8              450.0  ...                      2.723889
9              450.0  ...                      2.853591
10             452.0  ...                      2.691797
11             450.0  ...                      2.732059

[12 rows x 14 columns]

In [51]:
results[2]

Xr без коррекции  ...  Расстояние от реал до (Ur-Δ)
0         210.905955  ...                    864.272303
1         453.351541  ...                      2.381799
2         446.519832  ...                      1.418345
3         451.047561  ...                      2.242588
4         468.551844  ...                      3.800648
5         464.683763  ...                      3.065402
6         203.102738  ...                    793.072362
7         170.245815  ...                    919.758714
8         489.209281  ...                      6.448643
9         448.312245  ...                      2.873819
10        453.334036  ...                      2.752109
11        466.415381  ...                      3.333650

[12 rows x 14 columns]