# Задача потребителя

## Получение данных

Параметры модулирования:


>  Станция
    Novosibirsk(MRK)
    
    X
    452.28865
    Y
    3635.913158
    Z
    5203.397861

>  Спутники

*   1. 1/2
*   2. 2/1
*   3. 3/12
*   4. 4/6


In [0]:
import numpy as np
import pandas as pd
from scipy.optimize import fsolve

In [0]:
 required_coordinates = np.array([
        452.28865,
        3635.913158,
        5203.397861,
 ])

In [3]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('Загруженный "{name}" размером {length} байт'.format(
      name=fn, length=len(uploaded[fn])))

Saving reports.xls to reports.xls
Загруженный "reports.xls" размером 306688 байт


In [4]:
mod_data = pd.read_excel("reports.xls")
mod_data.head()

Time_mom  N_Sat            P1        Sat_X         Sat_Y        Sat_Z
0  01:47:00      1  23640.463423 -1403.143993  25077.821790 -4577.880104
1  01:47:30      1  23614.250832 -1400.494773  25096.862175 -4472.742878
2  01:48:00      1  23588.052424 -1397.739724  25115.469797 -4367.509327
3  01:48:30      1  23561.868740 -1394.880788  25133.643881 -4262.181717
4  01:49:00      1  23535.700307 -1391.919910  25151.383669 -4156.762322

In [5]:
by_time = mod_data.groupby(by='Time_mom')['N_Sat'].count() 
observed_more_than_two = by_time[by_time>2]
len(observed_more_than_two)

405

In [6]:
len(observed_more_than_two[observed_more_than_two>3])   # одновременно 4 никогда не наблюдаются

0

In [7]:
sample_time = observed_more_than_two.index[78]
sample = mod_data[mod_data['Time_mom'] == sample_time]
sample

Time_mom  N_Sat            P1         Sat_X         Sat_Y         Sat_Z
785  05:25:00      2  19052.577323   2184.905275  15349.310978  20129.689073
786  05:25:00      1  21106.787484 -11915.881636   3162.669722  22300.104699
787  05:25:00      3  21880.141257  16211.479975  18786.485990   6124.669437

## Предустановки

In [0]:
def get_Us_and_P(row):
    return np.array([row['Sat_X'],
                     row['Sat_Y'],
                     row['Sat_Z'],]), row['P1']

In [0]:
def distance(v1,v2):
    return np.sqrt(np.sum((v1-v2)**2))

In [0]:
def dir_cos(Us,Ur,Ro0):
    return (Us-Ur)/Ro0

## I способ расчета

In [11]:
sat_data = [get_Us_and_P(sample.iloc[i]) for i in range(3)]
sat_data

[(array([ 2184.90527483, 15349.3109776 , 20129.68907288]), 19052.5773226953),
 (array([-11915.8816357 ,   3162.66972196,  22300.10469944]), 21106.787484125),
 (array([16211.47997461, 18786.48599038,  6124.66943681]), 21880.1412569171)]

In [0]:
def to_solve_Ur_0(v,Sat_data):
    return [distance(v,u) - p for u,p in Sat_data]

In [13]:
to_solve_Ur_0(required_coordinates,sat_data)

[-0.02321069562822231, -0.0828553766150435, 0.002930710372311296]

In [14]:
%time Ur_0 = fsolve(to_solve_Ur_0, np.array([1.,1.,1.]), args=(sat_data))

Ur_0              

CPU times: user 993 µs, sys: 0 ns, total: 993 µs
Wall time: 988 µs


array([ 450.6806568 , 3637.66420946, 5202.18098915])

In [15]:
Ro = np.array([P_i for Us_i,P_i in sat_data])
Ro_0 = Ro.round()
Us = [Us_i for Us_i,P in sat_data]
Us

[array([ 2184.90527483, 15349.3109776 , 20129.68907288]),
 array([-11915.8816357 ,   3162.66972196,  22300.10469944]),
 array([16211.47997461, 18786.48599038,  6124.66943681])]

In [16]:
dir_cosines = [dir_cos(*vals) for vals in zip(Us,[Ur_0]*3,Ro_0)]
dir_cosines

[array([0.09102108, 0.61468781, 0.78347284]),
 array([-0.58589863, -0.02250412,  0.8100594 ]),
 array([0.72032904, 0.69235931, 0.04216126])]

In [0]:
def to_solve_deltas(deltas,cosines,ro_0,ro):
    return [(-p+p0+np.sum(np.array(deltas)*cos)) for cos,p0,p in zip(cosines,ro_0,ro)]

In [29]:
to_solve_deltas([.0,.0,.0,],dir_cosines,Ro_0,Ro)

[0.42267730470121023, 0.212515874998644, -0.14125691710069077]

In [30]:
%time deltas = fsolve(to_solve_deltas,[.0,.0,.0],args=(dir_cosines,Ro_0,Ro))
deltas

CPU times: user 0 ns, sys: 1.96 ms, total: 1.96 ms
Wall time: 4.82 ms


array([ 11.38832422, -12.1094908 ,   7.63817345])

In [21]:
print('Без смещений')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0)
print('разности в координатах\n', abs(required_coordinates - Ur_0))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0))

Без смещений
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 450.6806568  3637.66420946 5202.18098915]
разности в координатах
 [1.6079932  1.75105146 1.21687185]
расстояние между реальной и предполагаемой точками
 2.6706928744430445


In [34]:
print('Со смещениями + delta')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0+deltas)
print('разности в координатах\n', abs(required_coordinates - Ur_0-deltas))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0+deltas))

Со смещениями
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 462.06898102 3625.55471865 5209.8191626 ]
разности в координатах
 [ 9.78033102 10.35843935  6.4213016 ]
расстояние между реальной и предполагаемой точками
 15.626428087904301


In [0]:
print('Со смещениями - delta')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0-deltas)
print('разности в координатах\n', abs(required_coordinates - Ur_0+deltas))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0-deltas))

Со смещениями
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 462.06898102 3625.55471865 5209.8191626 ]
разности в координатах
 [ 9.78033102 10.35843935  6.4213016 ]
расстояние между реальной и предполагаемой точками
 15.626428087904301


## II способ расчета

In [45]:
print(sat_data)
print(Us)
print(Ro)

[(array([ 2184.90527483, 15349.3109776 , 20129.68907288]), 19052.5773226953), (array([-11915.8816357 ,   3162.66972196,  22300.10469944]), 21106.787484125), (array([16211.47997461, 18786.48599038,  6124.66943681]), 21880.1412569171)]
[array([ 2184.90527483, 15349.3109776 , 20129.68907288]), array([-11915.8816357 ,   3162.66972196,  22300.10469944]), array([16211.47997461, 18786.48599038,  6124.66943681])]
[19052.5773227  21106.78748413 21880.14125692]


In [41]:
%time Ur_0 = fsolve(to_solve_Ur_0, np.array([1.,1.,1.]), args=(sat_data)).round()
Ur_0              

CPU times: user 902 µs, sys: 0 ns, total: 902 µs
Wall time: 879 µs


array([ 451., 3638., 5202.])

In [47]:
Ro_0 = np.array([distance(Ur_0,Us_i) for Us_i in Us])
Ro_0

array([19052.48365365, 21107.12876204, 21879.68637162])

In [48]:
dir_cosines = [dir_cos(*vals) for vals in zip(Us,[Ur_0]*3,Ro_0)]
dir_cosines

[array([0.09100678, 0.61468684, 0.78350358]),
 array([-0.58591018, -0.02251989,  0.81006303]),
 array([0.72032477, 0.69235389, 0.04217014])]

In [49]:
%time deltas = fsolve(to_solve_deltas,[.0,.0,.0],args=(dir_cosines,Ro_0,Ro))
deltas

CPU times: user 1.54 ms, sys: 0 ns, total: 1.54 ms
Wall time: 2.19 ms


array([ 0.31926152,  0.33588008, -0.18104191])

In [50]:
print('Без смещений')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0)
print('разности в координатах\n', abs(required_coordinates - Ur_0))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0))

Без смещений
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 451. 3638. 5202.]
разности в координатах
 [1.28865  2.086842 1.397861]
расстояние между реальной и предполагаемой точками
 2.8230380321183715


In [53]:
print('Со смещениями - delta')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0-deltas)
print('разности в координатах\n', abs(required_coordinates - Ur_0+deltas))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0-deltas))

Со смещениями - delta
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 450.68073848 3637.66411992 5202.18104191]
разности в координатах
 [1.60791152 1.75096192 1.21681909]
расстояние между реальной и предполагаемой точками
 2.6705609482341104


In [54]:
print('Со смещениями + delta')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0+deltas)
print('разности в координатах\n', abs(required_coordinates - Ur_0-deltas))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0+deltas))

Со смещениями + delta
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 451.31926152 3638.33588008 5201.81895809]
разности в координатах
 [0.96938848 2.42272208 1.57890291]
расстояние между реальной и предполагаемой точками
 3.0499558559262883


## III способ расчета

In [0]:
Ro_0 = Ro.round()

In [59]:
%time Ur_0 = fsolve(to_solve_Ur_0, np.array([1.,1.,1.]), args=(list(zip(Us,Ro_0))))
Ur_0              

CPU times: user 889 µs, sys: 0 ns, total: 889 µs
Wall time: 886 µs


array([ 462.25086458, 3625.36858019, 5209.95564882])

In [60]:
dir_cosines = [dir_cos(*vals) for vals in zip(Us,[Ur_0]*3,Ro_0)]
dir_cosines

[array([0.09041381, 0.61533314, 0.78306479]),
 array([-0.58644679, -0.02192158,  0.80969105]),
 array([0.71980023, 0.69292127, 0.04180593])]

In [61]:
%time deltas = fsolve(to_solve_deltas,[.0,.0,.0],args=(dir_cosines,Ro_0,Ro))
deltas

CPU times: user 1.49 ms, sys: 52 µs, total: 1.54 ms
Wall time: 1.34 ms


array([ 11.75824137, -12.48807544,   7.91574599])

In [62]:
print('Без смещений')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0)
print('разности в координатах\n', abs(required_coordinates - Ur_0))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0))

Без смещений
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 462.25086458 3625.36858019 5209.95564882]
разности в координатах
 [ 9.96221458 10.54457781  6.55778782]
расстояние между реальной и предполагаемой точками
 15.919749418286411


In [63]:
print('Со смещениями - delta')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0-deltas)
print('разности в координатах\n', abs(required_coordinates - Ur_0+deltas))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0-deltas))

Со смещениями - delta
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 450.4926232  3637.85665563 5202.03990283]
разности в координатах
 [1.7960268  1.94349763 1.35795817]
расстояние между реальной и предполагаемой точками
 2.9743815625166876


In [64]:
print('Со смещениями + delta')
print('искомое\n', required_coordinates)
print('полученное\n', Ur_0+deltas)
print('разности в координатах\n', abs(required_coordinates - Ur_0-deltas))
print('расстояние между реальной и предполагаемой точками\n', distance(required_coordinates,Ur_0+deltas))

Со смещениями + delta
искомое
 [ 452.28865  3635.913158 5203.397861]
полученное
 [ 474.00910595 3612.88050475 5217.87139481]
разности в координатах
 [21.72045595 23.03265325 14.47353381]
расстояние между реальной и предполагаемой точками
 34.810407972929994


## Результаты

In [66]:
print('Δ','δ')

Δ δ


In [0]:
def ingot():
    return    {'Xr без коррекции':[],
               'Yr без коррекции':[],
               'Zr без коррекции':[],
               'ΔX':[],
               'ΔY':[],
               'ΔZ':[],}

In [0]:
def method_1(samples: list):
    res = ingot()
    for sample in samples:
        sat_data = [get_Us_and_P(sample.iloc[i]) for i in range(3)]
        Ur_0 = fsolve(to_solve_Ur_0, np.array([1.,1.,1.]), args=(sat_data))
        Ro = np.array([P_i for Us_i,P_i in sat_data])
        Ro_0 = Ro.round()
        Us = [Us_i for Us_i,P in sat_data]
        dir_cosines = [dir_cos(*vals) for vals in zip(Us,[Ur_0]*3,Ro_0)]
        deltas = fsolve(to_solve_deltas,[.0,.0,.0],args=(dir_cosines,Ro_0,Ro))
        for i,ax in enumerate(('X','Y','Z')):
           res[ax+'r без коррекции'].append(Ur_0[i])
           res['Δ'+ax].append(deltas[i])
    return res

In [0]:
def method_2(samples: list):
    res = ingot()
    for sample in samples:
        sat_data = [get_Us_and_P(sample.iloc[i]) for i in range(3)]
        Ro = np.array([P_i for Us_i,P_i in sat_data])
        Us = [Us_i for Us_i,P in sat_data]
        Ur_0 = fsolve(to_solve_Ur_0, np.array([1.,1.,1.]), args=(sat_data)).round()
        Ro_0 = np.array([distance(Ur_0,Us_i) for Us_i in Us])
        dir_cosines = [dir_cos(*vals) for vals in zip(Us,[Ur_0]*3,Ro_0)]
        deltas = fsolve(to_solve_deltas,[.0,.0,.0],args=(dir_cosines,Ro_0,Ro))
        for i,ax in enumerate(('X','Y','Z')):
           res[ax+'r без коррекции'].append(Ur_0[i])
           res['Δ'+ax].append(deltas[i])
    return res

In [0]:
def method_3(samples: list):
    res = ingot()
    for sample in samples:
        sat_data = [get_Us_and_P(sample.iloc[i]) for i in range(3)]
        Ro = np.array([P_i for Us_i,P_i in sat_data])
        Us = [Us_i for Us_i,P in sat_data]
        Ro_0 = Ro.round()
        Ur_0 = fsolve(to_solve_Ur_0, np.array([1.,1.,1.]), args=(list(zip(Us,Ro_0))))
        dir_cosines = [dir_cos(*vals) for vals in zip(Us,[Ur_0]*3,Ro_0)]
        deltas = fsolve(to_solve_deltas,[.0,.0,.0],args=(dir_cosines,Ro_0,Ro))
        for i,ax in enumerate(('X','Y','Z')):
           res[ax+'r без коррекции'].append(Ur_0[i])
           res['Δ'+ax].append(deltas[i])
    return res

In [0]:
from random import sample as some_samples

In [72]:
n_sample_time = some_samples(observed_more_than_two.index.to_list(), 12)
samples = [mod_data[mod_data['Time_mom'] == sample_time] for sample_time in n_sample_time]
samples[4:8]

[      Time_mom  N_Sat            P1         Sat_X         Sat_Y         Sat_Z
 1665  07:52:00      2  22797.102214 -20224.854103   4282.385819  14781.527912
 1666  07:52:00      3  19414.309175  -2591.632905  10724.703544  23019.050184
 1667  07:52:00      4  20258.056522  14697.783003  10829.685964  17681.547844,
       Time_mom  N_Sat            P1         Sat_X         Sat_Y         Sat_Z
 1079  06:14:00      2  19480.337107  -4734.848496   9726.494539  22965.154933
 1080  06:14:00      1  23166.568085 -18509.512818  -1619.420214  17431.064071
 1081  06:14:00      3  20186.330641  12930.758302  15907.933548  15261.883423,
       Time_mom  N_Sat            P1         Sat_X         Sat_Y         Sat_Z
 1599  07:41:00      2  22337.574802 -18794.335354   4423.674440  16513.105573
 1600  07:41:00      3  19317.962686   -529.011020  10979.680311  23044.039060
 1601  07:41:00      4  20577.455360  16201.444918  11194.953370  16077.981843,
       Time_mom  N_Sat            P1         Sat_

In [0]:
results = [pd.DataFrame(eval('method_'+str(i+1)+'(samples)')) for i in range(3)]

for df in results:
    to_pop = list()
    for sign in ('+','-'):
        for i,ax in enumerate(('X','Y','Z')):
            tmp = eval("df[ax+'r без коррекции']"+sign+
                       "df['Δ'+ax] - required_coordinates[i]" )
            df['{a}r {s} Δ{a} - {a} реал.'.format(a=ax,s=sign)] = tmp
            hs = str(i)+sign
            to_pop.append(hs)
            df[hs] = tmp**2
        df['Расстояние от реал до (Ur{s}Δ)'.format(s=sign)] = np.sqrt(
            df['0'+sign]+df['1'+sign]+df['2'+sign]
        )
    for hs in to_pop:
        df.pop(hs)
    to_pop.clear()

In [92]:
results[0]

Xr без коррекции  ...  Расстояние от реал до (Ur-Δ)
0         217.905615  ...                    793.349136
1         450.897530  ...                     29.372324
2         450.773399  ...                     34.636204
3         453.076604  ...                     18.060522
4         451.932368  ...                      5.272098
5         450.849867  ...                     19.196450
6         451.528518  ...                     11.235310
7         450.880169  ...                     22.340666
8         454.147681  ...                     12.113897
9         453.955781  ...                     19.881669
10        452.906904  ...                      3.033522
11        452.904778  ...                      6.800144

[12 rows x 14 columns]

In [93]:
results[1]

Xr без коррекции  ...  Расстояние от реал до (Ur-Δ)
0              218.0  ...                    771.287612
1              451.0  ...                      2.778468
2              451.0  ...                      2.609950
3              453.0  ...                      2.120202
4              452.0  ...                      3.100364
5              451.0  ...                      3.242332
6              452.0  ...                      4.583667
7              451.0  ...                      2.973909
8              454.0  ...                      6.395520
9              454.0  ...                      5.622403
10             453.0  ...                      1.411504
11             453.0  ...                      1.411209

[12 rows x 14 columns]

In [94]:
results[2]

Xr без коррекции  ...  Расстояние от реал до (Ur-Δ)
0         224.769369  ...                    771.995129
1         465.106320  ...                      3.357171
2         429.216328  ...                      3.621097
3         460.037114  ...                      2.394126
4         450.701445  ...                      3.153714
5         440.903399  ...                      3.595347
6         453.257335  ...                      4.640591
7         460.891372  ...                      3.271024
8         452.165917  ...                      6.466423
9         449.769484  ...                      6.039027
10        452.137268  ...                      1.412673
11        456.713162  ...                      1.440502

[12 rows x 14 columns]